//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Client.NormalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NormalService.INormalService")]
    public interface INormalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INormalService/DoWork", ReplyAction="http://tempuri.org/INormalService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INormalService/Show", ReplyAction="http://tempuri.org/INormalService/ShowResponse")]
        string Show(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INormalServiceChannel : WCF_Client.NormalService.INormalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NormalServiceClient : System.ServiceModel.ClientBase<WCF_Client.NormalService.INormalService>, WCF_Client.NormalService.INormalService {
        
        public NormalServiceClient() {
        }
        
        public NormalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NormalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NormalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NormalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public string Show(string data) {
            return base.Channel.Show(data);
        }
    }
}
